-- Create companies table
create table if not exists companies (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  logo text,
  color text,
  tags text[],
  category text,
  funding_amount numeric,
  global_rank integer,
  funding_data jsonb,
  competitors jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (optional, but good practice)
alter table companies enable row level security;

-- Create a policy that allows anyone to read (since we want public access for now)
create policy "Public companies are viewable by everyone"
  on companies for select
  using ( true );

-- Create a policy that allows authenticated users to insert
create policy "Authenticated users can insert companies"
  on companies for insert
  with check ( auth.role() = 'authenticated' );

-- Insert E-commerce companies with real-ish data
insert into companies (name, description, logo, color, tags, category, funding_amount, global_rank, funding_data, competitors)
values 
(
  'Shopify', 
  'Global commerce platform that powers millions of businesses worldwide.', 
  '🛍️', 
  '#96bf48', 
  ARRAY['E-commerce', 'SaaS', 'Retail', 'Platform'], 
  'E-commerce', 
  1200000000, 
  15, 
  '[
    {"name": "2020", "value": 800},
    {"name": "2021", "value": 1500},
    {"name": "2022", "value": 2200},
    {"name": "2023", "value": 3500},
    {"name": "2024", "value": 4800}
  ]',
  '[
    {"name": "BigCommerce", "valuation": "$4.5B", "employees": 1200, "initial": "B", "colorClass": "bg-blue-500", "growthClass": "text-accent"},
    {"name": "WooCommerce", "valuation": "$2.1B", "employees": 800, "initial": "W", "colorClass": "bg-purple-500", "growthClass": "text-accent"}
  ]'
),
(
  'Amazon', 
  'The world''s largest online retailer and cloud service provider.', 
  '📦', 
  '#FF9900', 
  ARRAY['E-commerce', 'Cloud', 'Logistics', 'AI'], 
  'E-commerce', 
  108000000000, 
  2, 
  '[
    {"name": "2020", "value": 25000},
    {"name": "2021", "value": 32000},
    {"name": "2022", "value": 45000},
    {"name": "2023", "value": 58000},
    {"name": "2024", "value": 72000}
  ]',
  '[
    {"name": "Walmart", "valuation": "$400B", "employees": 2300000, "initial": "W", "colorClass": "bg-blue-600", "growthClass": "text-accent"},
    {"name": "Alibaba", "valuation": "$200B", "employees": 250000, "initial": "A", "colorClass": "bg-orange-500", "growthClass": "text-red-500"}
  ]'
);
